version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
          - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/cache/:/etc/nginx/cache
          - ./webserver_data/logs/nginx/:/var/log/nginx
        ports:
          - "443:443"